services:
  fastapi_backend:
    build: .
    expose:
      - "8000"
    command: uvicorn database_service:app --host 0.0.0.0 --port 8000
    env_file:
      - .env

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fastapi_backend