version: '3.8'

services:
  fastapi_backend:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    container_name: stars_backend_dev
    ports:
      - "8080:8080"
    command: uvicorn src.database_service:app --host 0.0.0.0 --port 8080 --reload
    env_file:
      - ../.env
      - ../config/.env.docker
    environment:
      - ENVIRONMENT=development
      - FASTAPI_RELOAD=true
    volumes:
      - .:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    depends_on:
      - redis
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  redis:
    image: redis:alpine
    container_name: stars_redis_dev
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: redis-server --appendonly yes
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: stars_nginx_dev
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - fastapi_backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis_data_dev:

networks:
  default:
    name: stars_network_dev 