version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: docker-azurite-1
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    restart: always


  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file:
      - ../config/.env.development
    environment:
      - REDIS_HOST=redis
      - AZURE_STORAGE_CONNECTION_STRING=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;TableEndpoint=http://azurite:10002/devstoreaccount1;
    volumes:
      - ../src:/app/src
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - azurite
    working_dir: /app
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]



volumes:
  azurite_data:

networks:
  default:
    name: stars_network