name: Build and Push Container

on:
  push:
    branches: [ main ]
    paths:
      - 'database_service.py'
      - 'Dockerfile'
      - 'requirements.txt'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build and Push
        run: |
          docker build -t ghcr.io/hillcallum/starmap-service:latest .
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ghcr.io/hillcallum/starmap-service:latest